baseURL = 'https://leahwasser.come/'
languageCode = 'en-us'
title = 'Leah A Wasser'

# Customize theme parameters here
[params]
  author = "Leah A. Wasser"
  tagline = "Your tagline here"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 4
