name: Build and Jekyll site and run htmlproofer

on:
  push:
    branches:
      - '*'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: Use cache to shorten build time
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
              
      - name: Build Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
          jekyll_build_options: -d _site

      - name: Check HTML using htmlproofer
        uses: chabad360/htmlproofer@master
        with:
          directory: '_site'
          # The directory to scan
          arguments: --url-swap "https\:\/\/www\.leahwasser\.com\/images:/images" --http-status-ignore "301"
          # The arguments to pass to HTMLProofer