name: Build Hugo Site

on:
  push:
    branches: [ hugo ]
  pull_request:
    branches: [ hugo ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '22'

      - name: Cache Node modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm ci

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.118.2'
          extended: true

      - name: Build site (npm)
        run: npm run build

      - name: Upload public folder
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #v5.0.0
        with:
          name: hugo-public
          path: public
  # deploy:
  #   name: Deploy to GitHub Pages
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && (github.event.pull_request == null || github.event.pull_request.head.repo.fork == false)
  #   permissions:
  #     contents: read
  #     pages: write
  #     id-token: write
  #   # steps:
  #   #   - name: Deploy to GitHub Pages
  #   #     id: deployment
  #   #     uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5