name: Build Jekyll (PRs & branches) and Deploy (only main)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 1

      - name: Set up Ruby (with bundler cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site
        env:
          JEKYLL_ENV: production

      - name: Run htmlproofer (only on main; don't fail workflow)
        if: github.ref == 'refs/heads/main'
        uses: chabad360/htmlproofer@v2
        continue-on-error: true
        with:
          directory: '_site'
          arguments: --ignore-urls "https://www.linkedin.com/in/leah-wasser-0138883,https://fonts.googleapis.com,https://fonts.gstatic.com,https://docs.github.com/en/actions"

      - name: Upload Pages artifact (only on main)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Deploy to Pages
        uses: actions/deploy-pages@v1