name: Build Jekyll site, publish on main and run htmlproofer
# TODO: delete this...
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - '*'
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 1

      - name: Set up Ruby and run bundle install (auto cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Check HTML using htmlproofer
        uses: chabad360/htmlproofer@v2
        continue-on-error: true
        with:
          directory: '_site'
          arguments: --ignore-urls "https://www.linkedin.com/in/leah-wasser-0138883,https://fonts.googleapis.com,https://fonts.gstatic.com,https://docs.github.com/en/actions"
